/*
 * This file was automatically generated by Magic from servergardens.com
 */

import { Component, Inject } from '@angular/core';
import { MatDialogRef, MAT_DIALOG_DATA } from '@angular/material';

export class AuthModel {
  username: string;
  password: string;
}

/**
 * Your app's login component.
 *
 * This is the modal that encapsulates your login form
 */
@Component({
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent {

  public username: string;
  public password: string;

  public constructor(
    private dialogRef: MatDialogRef<LoginComponent>,
    @Inject(MAT_DIALOG_DATA) public data: AuthModel)
  { }

  public login() {
    this.dialogRef.close({
      username: this.username,
      password: this.password
    });
  }

  public close() {
    this.dialogRef.close();
  }
}
