USE [master]
GO

/****** Object:  Database [magic_auth]    Script Date: 05/12/2019 3:13:05 PM ******/
CREATE DATABASE [magic_auth]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'magic_auth', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\magic_auth.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'magic_auth_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\magic_auth_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [magic_auth] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [magic_auth].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [magic_auth] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [magic_auth] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [magic_auth] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [magic_auth] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [magic_auth] SET ARITHABORT OFF 
GO

ALTER DATABASE [magic_auth] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [magic_auth] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [magic_auth] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [magic_auth] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [magic_auth] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [magic_auth] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [magic_auth] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [magic_auth] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [magic_auth] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [magic_auth] SET  DISABLE_BROKER 
GO

ALTER DATABASE [magic_auth] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [magic_auth] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [magic_auth] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [magic_auth] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [magic_auth] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [magic_auth] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [magic_auth] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [magic_auth] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [magic_auth] SET  MULTI_USER 
GO

ALTER DATABASE [magic_auth] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [magic_auth] SET DB_CHAINING OFF 
GO

ALTER DATABASE [magic_auth] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [magic_auth] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [magic_auth] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [magic_auth] SET QUERY_STORE = OFF
GO

ALTER DATABASE [magic_auth] SET  READ_WRITE 
GO


USE [magic_auth]
GO

/****** Object:  Table [dbo].[users]    Script Date: 05/12/2019 3:13:25 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[users](
	[username] [nvarchar](128) NOT NULL,
	[password] [nvarchar](128) NOT NULL,
 CONSTRAINT [PK_users] PRIMARY KEY CLUSTERED 
(
	[username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [magic_auth]
GO

/****** Object:  Table [dbo].[roles]    Script Date: 05/12/2019 3:13:38 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[roles](
	[name] [nvarchar](128) NOT NULL,
 CONSTRAINT [PK_roles] PRIMARY KEY CLUSTERED 
(
	[name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [magic_auth]
GO

/****** Object:  Table [dbo].[users_roles]    Script Date: 05/12/2019 3:13:46 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[users_roles](
	[user] [nvarchar](128) NOT NULL,
	[role] [nvarchar](128) NOT NULL,
 CONSTRAINT [PK_users_roles] PRIMARY KEY CLUSTERED 
(
	[user] ASC,
	[role] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO



insert into roles (name) values ('root');
insert into roles (name) values ('user');
insert into roles (name) values ('guest');
