/*
 * This file was automatically generated by Magic from servergardens.com
 */

import { Observable } from 'rxjs';
import { Component, OnInit, Input } from '@angular/core';
import { HttpService } from '../../services/http-service';

@Component({
  selector: 'app-selector',
  templateUrl: './selector.component.html',
  styleUrls: ['./selector.component.scss']
})
export class SelectorComponent implements OnInit {

  @Input() public model: string;
  @Input() public key: string;
  @Input() public value: string;
  @Input() public getItems: Observable<any>;
  public items: any[];

  constructor(private service: HttpService) { }

  ngOnInit() {
    this.getItems.subscribe(res => {
      this.items = res;
    });
  }
}
